#version 460

layout(set = 0, binding = 0) buffer WaterHeightBuffer0 {
    float s_WaterHeight0[256 * 256];
};

layout(set = 0, binding = 1) buffer WaterHeightBuffer1 {
    float s_WaterHeight1[256 * 256];
};

layout(set = 0, binding = 2, rgba8) uniform image2D u_WaterNormal;

layout(push_constant) uniform PushConstants {
    uint pc_InputBufferIndex;
};

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

float loadHeight(ivec2 imageCoords, bool inputBuffer)
{
    if (imageCoords.x < 0 || imageCoords.y < 0 || imageCoords.x > 255 || imageCoords.y > 255)
        return 0;

    bool buffer0 = pc_InputBufferIndex == 0;
    if (!inputBuffer)
        buffer0 = !buffer0;

    const uint idx = imageCoords.y * 255 + imageCoords.x;
    if (buffer0)
        return s_WaterHeight0[idx];
    else
        return s_WaterHeight1[idx];
}

void main()
{
    const ivec2 imageCoords = ivec2(gl_GlobalInvocationID.xy);

    const float diffX = loadHeight(ivec2(imageCoords.x + 1, imageCoords.y), false) -
                        loadHeight(ivec2(imageCoords.x - 1, imageCoords.y), false);
    const float diffY = loadHeight(ivec2(imageCoords.x, imageCoords.y + 1), false) - 
                        loadHeight(ivec2(imageCoords.x, imageCoords.y - 1), false);

    const float diffTangent = (2.0f / 256) * 2.0f;

    const vec3 normal = normalize(cross(
        normalize(vec3(diffTangent, 0.0f, diffX)),
        normalize(vec3(0.0f, diffTangent, diffY))
    ));

    imageStore(u_WaterNormal, imageCoords, vec4((normal + 1.0f) / 2.0f, 1.0f));
}